version: '3.8'

services:
  smart-retail-api:
    build: .
    ports:
      - "8001:8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
    volumes:
      - ./artifacts:/app/artifacts
      - ./chroma_db:/app/chroma_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health/z"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
